services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrongPassword123!
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  backend:
    build:
      context: ./MyBackend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5234:5234"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=todo_db;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

volumes:
  mssql_data:
